from __future__ import annotations
import argparse, json, os, shutil, sys
from pathlib import Path

APP_DIR = Path(__file__).resolve().parents[1]
FACTORY = APP_DIR / "factory"

APP_ID = "12-app-factory-ia"

def default_data_root() -> Path:
    """Global Factory configuration/state. User-generated source does not live here."""
    override = os.environ.get("BINARIO_APP_FACTORY_DATA_ROOT")
    if override:
        return Path(override).expanduser().resolve()
    return (Path.home() / "Library" / "Application Support" / "Binario IA" / "App Factory").resolve()

def default_workspace_root() -> Path:
    """Human-visible source workspaces for Apps generated by the Factory."""
    override = os.environ.get("BINARIO_APP_FACTORY_WORKSPACE_ROOT")
    if override:
        return Path(override).expanduser().resolve()
    projects = Path(os.environ.get("BINARIO_PROJECTS_HOME") or (Path.home() / "Documents" / "Binario IA" / "Projects")).expanduser().resolve()
    return projects / "_App Factory"

def _safe_replace_with_symlink(local: Path, target: Path, seed_text: str | None = None) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    if seed_text is not None and not target.exists():
        target.write_text(seed_text, encoding="utf-8")
    if local.is_symlink():
        try:
            if local.resolve() == target.resolve():
                return
        except Exception:
            pass
        local.unlink()
    elif local.exists():
        if local.is_dir():
            if not target.exists():
                shutil.copytree(local, target)
            shutil.rmtree(local)
        else:
            if not target.exists():
                shutil.copy2(local, target)
            local.unlink()
    local.parent.mkdir(parents=True, exist_ok=True)
    local.symlink_to(target, target_is_directory=target.is_dir())

def prepare_runtime(factory_root: Path = FACTORY, data_root: Path | None = None) -> dict:
    factory_root = Path(factory_root).resolve()
    data_root = Path(data_root or default_data_root()).expanduser().resolve()
    data_root.mkdir(parents=True, exist_ok=True)
    workspace = default_workspace_root()
    state = data_root / "state"
    workspace.mkdir(parents=True, exist_ok=True)
    state.mkdir(parents=True, exist_ok=True)
    registry = data_root / "projects-registry.json"
    seed = json.dumps({"schemaVersion": 1, "projects": []}, indent=2, ensure_ascii=False) + "\n"
    _safe_replace_with_symlink(factory_root / "config" / "projects-registry.json", registry, seed)
    _safe_replace_with_symlink(factory_root / "workspace", workspace)
    _safe_replace_with_symlink(factory_root / ".sb-state", state)
    return {
        "factory": str(factory_root),
        "data_root": str(data_root),
        "workspace": str(workspace),
        "registry": str(registry),
        "state": str(state),
    }

def main() -> int:
    ap = argparse.ArgumentParser(description="Binario IA · App Factory IA")
    ap.add_argument("--host", default="127.0.0.1")
    ap.add_argument("--port", type=int, default=8790)
    ap.add_argument("--no-browser", action="store_true")
    args = ap.parse_args()
    info = prepare_runtime()
    env = os.environ.copy()
    env["BINARIO_APP_FACTORY_DATA_ROOT"] = info["data_root"]
    env.setdefault("BINARIO_SERVICE_ID", "binario-v0130-app-12-app-factory-ia")
    env["SB_FACTORY_EMBEDDED_IN_BINARIO_IA"] = "1"
    server = FACTORY / "console" / "server.py"
    argv = [sys.executable, str(server), "--host", args.host, "--port", str(args.port)]
    if args.no_browser:
        argv.append("--no-open")
    else:
        # El Hub abre la URL devuelta. Evitamos doble apertura.
        argv.append("--no-open")
    os.chdir(FACTORY)
    os.execve(sys.executable, argv, env)
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
