const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];let boot=null,current=null,activeStep='business',chatHistory=[];
const steps=[['business','Negocio'],['knowledge','Conocimiento'],['intents','Intents'],['flow','Flujo'],['model','Modelo'],['simulate','Simular'],['tests','Tests'],['channel','Canal'],['publish','Publicar'],['observe','Observar']];
async function api(path,opt={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...opt});const j=await r.json();if(!r.ok)throw new Error(j.error||r.statusText);return j}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function loadBoot(){boot=await api('/api/bootstrap');try{let h=await api('/api/hub-url');$('#aiControlLink').href=(h.url||'http://127.0.0.1:8780/').replace(/\/$/,'')+'/ai'}catch(e){}renderWorkspaceContext(boot.workspace_context);renderProjects();if(boot.projects[0])await openProject(boot.projects[0].id)}
function renderWorkspaceContext(c){if(!$('#workspaceContext'))return;c=c||{};$('#contextStatus').textContent=c.available?`${c.counts?.included||0} elementos · ${c.status}`:'Standalone';$('#workspaceContext').innerHTML=c.available?(c.items||[]).slice(0,8).map(x=>`<div><b>${esc(x.memory_type)}</b> · ${esc(x.title||'')}<br><span class="muted">${esc(x.content||'')}</span></div>`).join(''):'Sin contexto de Workspace activo.'}
function renderProjects(){const box=$('#projects');box.innerHTML=(boot?.projects||[]).map(p=>`<div class="project ${current?.id===p.id?'active':''}" onclick="openProject('${p.id}')"><b>${esc(p.name)}</b><small>${esc(p.current_step||'business')} · readiness ${p.readiness||0}%</small></div>`).join('')||'<div class="muted">Aún no hay agentes.</div>'}
async function createProject(){const name=prompt('Nombre del agente','Asistente Comercial')||'Nuevo agente';const p=await api('/api/projects',{method:'POST',body:JSON.stringify({name,business_name:name})});boot.projects.unshift({id:p.id,name:p.name});await openProject(p.id)}
async function openProject(id){current=await api('/api/projects/'+id);$('#empty').hidden=true;$('#studio').hidden=false;fill();renderProjects();showStep(current.current_step||'business')}
function fill(){if(!current)return;$('#projectTitle').textContent=current.name;$('#statusLine').textContent=`${current.status} · actualizado ${new Date(current.updated_at).toLocaleString()}`;$('#name').value=current.name||'';let b=current.business||{};$('#businessName').value=b.name||'';$('#purpose').value=b.purpose||'';$('#audience').value=b.audience||'';$('#tone').value=b.tone||'cercano-profesional';$('#hours').value=b.hours||'';$('#welcome').value=b.welcome||'';$('#handoff').value=b.handoff||'';$('#modelProfile').value=current.model?.profile||'balanced';let route=current.model?.last_route;$('#modelBadge').textContent=`IA: ${route?.chosen||current.model?.profile||'balanced'}`;$('#readinessBadge').textContent=`Readiness ${current.publish?.readiness||0}%`;renderSteps();renderKnowledge();renderIntents();renderFlow();renderTests();fillChannel();renderReadiness(exportLocalReadiness());loadActivity();resolveModelUI()}
function collect(){current.name=$('#name').value.trim()||current.name;current.business={...current.business,name:$('#businessName').value,purpose:$('#purpose').value,audience:$('#audience').value,tone:$('#tone').value,hours:$('#hours').value,welcome:$('#welcome').value,handoff:$('#handoff').value};current.model={...current.model,profile:$('#modelProfile').value};current.channel={...current.channel,type:$('#channelType').value,centric_channel:$('#centricChannel').value,phone_number_id:$('#phoneId').value,waba_id:$('#wabaId').value,webhook_url:$('#webhookUrl').value};return current}
async function save(rebuild=false){collect();current.current_step=activeStep;current=await api(`/api/projects/${current.id}/save`,{method:'POST',body:JSON.stringify({project:current,rebuild_flow:rebuild})});fill();return current}
async function snapshot(){await save();await api(`/api/projects/${current.id}/snapshot`,{method:'POST',body:JSON.stringify({label:'manual'})});alert('Snapshot creado')}
function renderSteps(){const done=steps.findIndex(x=>x[0]===current.current_step);$('#steps').innerHTML=steps.map(([id,label],i)=>`<button class="step ${activeStep===id?'active':''}" onclick="showStep('${id}')">${i+1}. ${label}${i<done?' ✓':''}</button>`).join('')}
function showStep(id){activeStep=id;$$('.step-panel').forEach(x=>x.hidden=x.dataset.step!==id);renderSteps();if(id==='observe')loadActivity();if(id==='publish')checkReadiness()}
function renderTrainingDocuments(){let rows=current?.knowledge_documents||[];$('#trainingDocuments').innerHTML=rows.length?`<div class="trainingDocsHead"><div><h4>Bloques importados de documentos</h4><p class="muted">Revísalos antes de activarlos. Un bloque desactivado no se usa para responder.</p></div><button onclick="approveTrainingDocs(true)">Aprobar todos</button></div>${rows.map((d,i)=>`<div class="item trainingDoc ${d.enabled?'approved':''}"><div class="itemGrid"><label class="wide"><span><input type="checkbox" ${d.enabled?'checked':''} onchange="current.knowledge_documents[${i}].enabled=this.checked;renderTrainingDocuments()"> Usar como conocimiento aprobado</span><textarea oninput="current.knowledge_documents[${i}].text=this.value">${esc(d.text||'')}</textarea></label></div><div class="small">${esc(d.title||'Documento')} · ${esc(d.source?.file||'')}</div></div>`).join('')}`:''}
function renderKnowledge(){$('#knowledge').innerHTML=(current.knowledge||[]).map((k,i)=>`<div class="item"><div class="itemGrid"><label>Título<input value="${esc(k.title||'')}" oninput="current.knowledge[${i}].title=this.value"></label><label>Pregunta<input value="${esc(k.question||'')}" oninput="current.knowledge[${i}].question=this.value"></label><label class="wide">Respuesta aprobada<textarea oninput="current.knowledge[${i}].answer=this.value">${esc(k.answer||'')}</textarea></label></div><div class="tools"><button onclick="current.knowledge.splice(${i},1);renderKnowledge()">Eliminar</button></div></div>`).join('')||'<p class="muted">Añade una FAQ o importa conocimiento desde un archivo.</p>';renderTrainingDocuments()}
function addKnowledge(){current.knowledge.push({id:'kb-'+Date.now(),title:'Nueva FAQ',question:'',answer:'',enabled:true});renderKnowledge()}
function fileBase64(file){return new Promise((resolve,reject)=>{let r=new FileReader();r.onload=()=>resolve(String(r.result||'').split(',').pop()||'');r.onerror=()=>reject(r.error||new Error('No se pudo leer el archivo'));r.readAsDataURL(file)})}
async function importTraining(){if(!current)return alert('Abre o crea un agente primero.');let file=$('#trainingFile')?.files?.[0];if(!file)return alert('Selecciona un archivo de entrenamiento.');if(file.size>12*1024*1024)return alert('Máximo 12 MB por archivo.');let btn=$('#importTrainingBtn'),status=$('#trainingStatus');btn.disabled=true;status.textContent='Importando y estructurando conocimiento…';try{let content_b64=await fileBase64(file);let r=await api(`/api/projects/${current.id}/training-import`,{method:'POST',body:JSON.stringify({filename:file.name,content_b64})});current=r.project;fill();status.textContent=`Importado: ${r.added.qa} Q&A · ${r.added.document_chunks} bloques de documento${r.documents_require_approval?' · revisa/aprueba los bloques antes de usarlos':''}`;$('#trainingFile').value=''}catch(e){status.textContent='Error: '+e.message}finally{btn.disabled=false}}
async function approveTrainingDocs(enabled=true){if(!current)return;let r=await api(`/api/projects/${current.id}/training-approve-docs`,{method:'POST',body:JSON.stringify({enabled})});current=r.project;fill()}
function renderIntents(){$('#intents').innerHTML=(current.intents||[]).map((it,i)=>`<div class="item"><div class="itemGrid"><label>ID<input value="${esc(it.id)}" oninput="current.intents[${i}].id=this.value"></label><label>Nombre<input value="${esc(it.label||'')}" oninput="current.intents[${i}].label=this.value"></label><label class="wide">Ejemplos (separados por coma)<input value="${esc((it.examples||[]).join(', '))}" oninput="current.intents[${i}].examples=this.value.split(',').map(x=>x.trim()).filter(Boolean)"></label><label>Acción<select onchange="current.intents[${i}].action=this.value"><option ${it.action==='knowledge'?'selected':''}>knowledge</option><option ${it.action==='collect'?'selected':''}>collect</option><option ${it.action==='handoff'?'selected':''}>handoff</option><option ${it.action==='message'?'selected':''}>message</option></select></label><label>Respuesta<input value="${esc(it.response||'')}" oninput="current.intents[${i}].response=this.value"></label></div><div class="tools"><button onclick="current.intents.splice(${i},1);renderIntents()">Eliminar</button></div></div>`).join('');$('#variables').innerHTML=(current.variables||[]).map((v,i)=>`<div class="item"><div class="itemGrid"><label>ID<input value="${esc(v.id)}" oninput="current.variables[${i}].id=this.value"></label><label>Etiqueta<input value="${esc(v.label||'')}" oninput="current.variables[${i}].label=this.value"></label><label>Prompt<input value="${esc(v.prompt||'')}" oninput="current.variables[${i}].prompt=this.value"></label><label>Obligatoria<select onchange="current.variables[${i}].required=this.value==='true'"><option value="false" ${!v.required?'selected':''}>No</option><option value="true" ${v.required?'selected':''}>Sí</option></select></label></div></div>`).join('')}
function addIntent(){current.intents.push({id:'intent-'+Date.now(),label:'Nuevo intent',examples:[],response:'',action:'message'});renderIntents()} function addVariable(){current.variables.push({id:'var-'+Date.now(),label:'Variable',type:'text',required:false,prompt:''});renderIntents()}
function renderFlow(){$('#flow').innerHTML=(current.flow?.nodes||[]).map(n=>`<div class="node"><div class="type">${esc(n.type)}</div><b>${esc(n.label||n.id)}</b><p>${esc(n.text||'')}</p></div>`).join('')}
async function rebuildFlow(){await save(true);renderFlow()}
async function resolveModelUI(){let r=boot?.ai?.routes?.['03-agente-ia-whatsapp'];if(!r)return;let m=r.chosen||{};let price=(m.input_usd_mtok!=null&&m.output_usd_mtok!=null)?`$${m.input_usd_mtok}/1M entrada · $${m.output_usd_mtok}/1M salida`:'costo no definido';$('#routeInfo').innerHTML=`Perfil: <b>${esc(current.model?.profile||r.profile)}</b><br>Ruta disponible: <b>${esc(m.label||m.id||'fallback local')}</b> · ${esc(m.provider||'local')}<br>Referencia de costo: <b>${esc(price)}</b><br>Sandbox de pruebas: <b>local determinista</b>`}
$('#modelProfile')?.addEventListener('change',async()=>{if(!current)return;current.model.profile=$('#modelProfile').value;await api('/api/ai/profile',{method:'POST',body:JSON.stringify({profile:current.model.profile})});boot=await api('/api/bootstrap');await save();resolveModelUI()})
async function sendChat(){let msg=$('#chatMessage').value.trim();if(!msg)return;$('#chatMessage').value='';appendBubble('user',msg);await save();let r=await api(`/api/projects/${current.id}/simulate`,{method:'POST',body:JSON.stringify({message:msg,history:chatHistory})});chatHistory.push({role:'user',content:msg},{role:'assistant',content:r.assistant});appendBubble('bot',r.assistant);$('#simMeta').textContent=`Intent: ${r.intent_label||'fallback'} · confianza ${r.confidence} · ${r.source} · ${r.handoff?'handoff':'sin handoff'} · ejecución ${r.execution_mode}`;current.tests.last_simulation=r;current.current_step='simulate';fill()}
function appendBubble(cls,text){let d=document.createElement('div');d.className='bubble '+cls;d.textContent=text;$('#chatLog').appendChild(d);$('#chatLog').scrollTop=99999}
function renderTests(){$('#testCases').innerHTML=(current.tests?.cases||[]).map((c,i)=>`<div class="item"><div class="itemGrid"><label>Mensaje<input value="${esc(c.message||'')}" oninput="current.tests.cases[${i}].message=this.value"></label><label>Intent esperado<input value="${esc(c.expected_intent||'')}" oninput="current.tests.cases[${i}].expected_intent=this.value"></label><label>Debe escalar<select onchange="current.tests.cases[${i}].expect_handoff=this.value==='true'"><option value="false" ${!c.expect_handoff?'selected':''}>No</option><option value="true" ${c.expect_handoff?'selected':''}>Sí</option></select></label></div></div>`).join('')||'<p class="muted">Añade casos para certificar el comportamiento.</p>'}
function addTest(){current.tests.cases.push({message:'',expected_intent:'',expect_handoff:false});renderTests()} async function runTests(){await save();let r=await api(`/api/projects/${current.id}/tests`,{method:'POST',body:JSON.stringify({cases:current.tests.cases})});$('#testResult').textContent=JSON.stringify(r,null,2);current.tests.last_run=r;current.current_step='tests';fill()}
function fillChannel(){let c=current.channel||{};$('#channelType').value=c.type||'sandbox';$('#centricChannel').value=c.centric_channel||'';$('#phoneId').value=c.phone_number_id||'';$('#wabaId').value=c.waba_id||'';$('#webhookUrl').value=c.webhook_url||'';$('#channelStatus').textContent=`Estado: ${c.status||'draft'}`}
async function saveChannel(){collect();let r=await api(`/api/projects/${current.id}/channel`,{method:'POST',body:JSON.stringify({channel:current.channel})});current.channel=r.channel;fill();$('#channelStatus').textContent=`Estado: ${r.channel.status} · token ${r.secret.configured?'configurado':'no configurado'}`}
async function saveToken(){let v=$('#waToken').value;if(!v)return alert('Pega un token primero');try{let r=await api('/api/channel/secret',{method:'POST',body:JSON.stringify({value:v})});$('#waToken').value='';alert(r.configured?'Guardado en Keychain':'No se pudo guardar')}catch(e){alert(e.message)}}
function exportLocalReadiness(){let checks={business:!!current?.business?.name,knowledge:(current?.knowledge?.length||0)>=1,intents:(current?.intents?.length||0)>=2,flow:(current?.flow?.nodes?.length||0)>=4,model:!!current?.model?.profile,simulation:!!current?.tests?.last_simulation,tests:!!current?.tests?.last_run?.passed,handoff:!!current?.business?.handoff};let score=Math.round(Object.values(checks).filter(Boolean).length/Object.keys(checks).length*100);return {checks,score,ready:score>=75&&checks.simulation&&checks.tests}}
function renderReadiness(r){$('#readiness').innerHTML=`<h2>${r.score}%</h2><div class="readinessGrid">${Object.entries(r.checks).map(([k,v])=>`<div class="check ${v?'ok':'no'}">${v?'✓':'○'} ${esc(k)}</div>`).join('')}</div>`;$('#readinessBadge').textContent=`Readiness ${r.score}%`}
async function checkReadiness(){await save();let r=await api(`/api/projects/${current.id}/readiness`,{method:'POST',body:'{}'});current.publish.readiness=r.score;renderReadiness(r);return r}
async function exportProject(){let r=await checkReadiness();if(!r.ready&&!confirm(`Readiness ${r.score}%. ¿Exportar de todas formas?`))return;let x=await api(`/api/projects/${current.id}/export`,{method:'POST',body:'{}'});$('#exportResult').innerHTML=`<div class="infoCard"><b>Paquete creado</b><br>${esc(x.zip)}<br>Readiness ${x.readiness.score}%</div>`;current.publish.last_export=x;fill()}
async function loadActivity(){if(!current)return;let r=await api(`/api/projects/${current.id}/activity`);$('#activity').innerHTML=(r.activity||[]).slice().reverse().map(x=>`<div class="activityItem"><b>${esc(x.event)}</b><br><small>${new Date(x.timestamp).toLocaleString()}</small><div>${esc(JSON.stringify(x.detail||{}))}</div></div>`).join('')||'<p class="muted">Sin actividad todavía.</p>'}
async function addObservation(){let text=prompt('Observación / mejora detectada');if(!text)return;await api(`/api/projects/${current.id}/observe`,{method:'POST',body:JSON.stringify({text})});loadActivity()}
$('#newProject').onclick=createProject;$('#saveBtn').onclick=()=>save();$('#snapshotBtn').onclick=snapshot;window.createProject=createProject;loadBoot().catch(e=>{console.error(e);alert('No se pudo iniciar Agent Studio: '+e.message)});